services:
  caddy:
    build:
      context: .
      args:
        DNS_PLUGIN: ${CADDY_DNS_PLUGIN:-porkbun}
    restart: unless-stopped
    network_mode: "host"
    env_file: ../.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
