services:
  miniflux-db:
    image: postgres:16
    container_name: miniflux-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: miniflux
      POSTGRES_PASSWORD: ${MINIFLUX_DB_PASS}
      POSTGRES_DB: miniflux
    volumes:
      - ${DATA_ROOT}/miniflux/db:/var/lib/postgresql/data

  miniflux:
    image: miniflux/miniflux:2.2.17
    container_name: miniflux
    restart: unless-stopped
    depends_on:
      - miniflux-db
    ports:
      - "9090:8080"
    environment:
      DATABASE_URL: postgres://miniflux:${MINIFLUX_DB_PASS}@miniflux-db/miniflux?sslmode=disable
      RUN_MIGRATIONS: "1"
      CREATE_ADMIN: "1"
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: ${MINIFLUX_ADMIN_PASS}
      POLLING_FREQUENCY: "60"
